env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: source
globals:
  log: false
rules:
  indent:
    - 2
    - 2
    - 
      VariableDeclarator: 2
      SwitchCase: 1
  linebreak-style:
    - 2
    - unix
  quotes:
    - 2
    - single
  semi:
    - 2
    - always
  max-len:
    - 2
    - 80
    - 4
  complexity:
    - 1
    - 6
  no-undef: 
    - 2
  no-use-before-define:
    - 2
    - nofunc
  no-console:
    - 0
  no-unused-vars:
    - 2
    - local
